# Generated by Django 5.2 on 2025-07-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('soat', models.DateTimeField()),
                ('tecnomechanical', models.DateTimeField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
