# Generated by Django 5.2 on 2025-07-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_driver_id_driver_created_at_driver_user_and_more'),
        ('travel', '0002_alter_travel_vehicle_travel_chk_price_positive_and_more'),
        ('vehicle', '0002_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vechicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='driver.driver'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['intermunicipal', 'metropolitano', 'campus'])), name='category_check'),
        ),
    ]
