# Generated by Django 5.2 on 2025-07-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_delete_vechicle_vehicle_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='soat',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tecnomechanical',
            field=models.DateField(),
        ),
    ]
