# Generated by Django 5.2 on 2025-07-24 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_remove_driver_id_driver_created_at_driver_user_and_more'),
        ('travel', '0002_alter_travel_vehicle_travel_chk_price_positive_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='driver.driver')),
                ('travel', models.ForeignKey(db_column='travel_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='travel.travel')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments_given', to='users.users')),
            ],
            options={
                'db_table': 'assessment',
                'constraints': [models.UniqueConstraint(fields=('travel', 'user'), name='unique_user_travel_assessment')],
            },
        ),
    ]
