# Generated by Django 5.2 on 2025-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=50)),
                ('institutional_email', models.EmailField(max_length=254)),
                ('student_code', models.CharField(max_length=100)),
                ('udocument', models.TextField()),
                ('institutinal_carne', models.TextField()),
                ('direction', models.TextField()),
                ('uphone', models.CharField(max_length=50)),
                ('upassword', models.TextField()),
                ('institution_id', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
