# Generated by Django 5.2 on 2025-05-29 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_alter_institution_email_alter_institution_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('admin', 'Administrador'), ('driver', 'Conductor/a'), ('student', 'Estudiante'), ('employee', 'Empleado/a'), ('teacher', 'Profesor/a')], max_length=20)),
                ('institutional_mail', models.EmailField(max_length=254)),
                ('student_code', models.CharField(max_length=100)),
                ('udocument', models.CharField(max_length=50)),
                ('institutional_carne', models.ImageField(blank=True, null=True, upload_to='carne/')),
                ('direction', models.TextField()),
                ('uphone', models.CharField(max_length=50)),
                ('upassword', models.CharField(max_length=255)),
                ('user_state', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=50)),
                ('driver_state', models.CharField(default='ninguno', max_length=50)),
                ('institution', models.ForeignKey(blank=True, db_column='institution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='institutions.institution')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
