# Generated by Django 5.2 on 2025-05-27 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_institution_email_alter_institution_phone'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='institutional_email',
            new_name='institutional_mail',
        ),
        migrations.RemoveField(
            model_name='users',
            name='institutinal_carne',
        ),
        migrations.RemoveField(
            model_name='users',
            name='institution_id',
        ),
        migrations.AddField(
            model_name='users',
            name='driver_state',
            field=models.CharField(default='ninguno', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='institution',
            field=models.ForeignKey(blank=True, db_column='institution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='users',
            name='institutional_carne',
            field=models.ImageField(blank=True, null=True, upload_to='carne/'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='udocument',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='upassword',
            field=models.CharField(max_length=255),
        ),
    ]
