# Generated by Django 5.2 on 2025-07-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_driver_id_driver_created_at_driver_user_and_more'),
        ('route', '0003_alter_route_driver'),
        ('travel', '0001_initial'),
        ('vehicle', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='travel',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='chk_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='travel',
            constraint=models.CheckConstraint(condition=models.Q(('travel_state__in', ['scheduled', 'in_progress', 'completed', 'cancelled'])), name='travel_travel_state_check'),
        ),
    ]
