# Generated by Django 5.2 on 2025-05-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('validate_state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
    ]
