# Generated by Django 5.2 on 2025-07-19 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(db_column='id', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver', serialize=False, to='users.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='validate_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(condition=models.Q(('validate_state__in', ['pending', 'approved', 'rejected'])), name='validate_state_check'),
        ),
    ]
