# Generated by Django 5.2 on 2025-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id_institution', models.AutoField(primary_key=True, serialize=False)),
                ('official_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('istate', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#6a5acd', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('ipassword', models.CharField(max_length=128)),
                ('validate_state', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
    ]
