# Generated by Django 5.2 on 2025-07-19 20:10

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_driver_id_driver_created_at_driver_user_and_more'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='origin',
            new_name='startLocation',
        ),
        migrations.RemoveField(
            model_name='route',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='driver.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='endPointCoords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=django.utils.timezone.now, size=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='startPointCoords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=django.utils.timezone.now, size=2),
            preserve_default=False,
        ),
    ]
