# Generated by Django 5.2 on 2025-07-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_driver_id_driver_created_at_driver_user_and_more'),
        ('route', '0002_rename_origin_route_startlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='driver.driver'),
        ),
    ]
