# Generated by Django 5.2 on 2025-07-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0002_alter_travel_vehicle_travel_chk_price_positive_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('travel', models.ForeignKey(db_column='id_travel', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='travel.travel')),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.users')),
            ],
            options={
                'db_table': 'realize',
                'unique_together': {('user', 'travel')},
            },
        ),
    ]
