# Generated by Django 5.2 on 2025-07-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realize', '0001_initial'),
        ('travel', '0002_alter_travel_vehicle_travel_chk_price_positive_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realize',
            name='reservation_date',
        ),
        migrations.AlterField(
            model_name='realize',
            name='travel',
            field=models.ForeignKey(db_column='id_travel', on_delete=django.db.models.deletion.CASCADE, related_name='realize', to='travel.travel'),
        ),
        migrations.AlterField(
            model_name='realize',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='realize', to='users.users'),
        ),
    ]
