# Generated by Django 5.2 on 2025-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realize', '0002_remove_realize_reservation_date_alter_realize_travel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realize',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
