# Generated by Django 5.2 on 2025-05-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'managed': False},
        ),
    ]
